---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "kustomize-app"
spec:
  project: default
  source:
    repoURL: https://github.com/juangb/argo-kustomize.git
    targetRevision: HEAD
    path: "kustomize-app"
  destination:
    server: https://kubernetes.default.svc
    namespace: "test-app"
  syncPolicy:
    syncOptions:
    - CreateNamespace=true 
