---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmap.yml

patches:
  - target:
      kind: ConfigMap
    patch: |-
      - op: add
        path: /data/othervariable
        value: whatever
      



